//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krkadoni.SESE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krkadoni.SESE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of.
        /// </summary>
        internal static string COPYOF {
            get {
                return ResourceManager.GetString("COPYOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        internal static string DELETING {
            get {
                return ResourceManager.GetString("DELETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string DOWNLOADING {
            get {
                return ResourceManager.GetString("DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading.
        /// </summary>
        internal static string ERROR_DOWNLOADING {
            get {
                return ResourceManager.GetString("ERROR_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load services..
        /// </summary>
        internal static string ERROR_FAILED_SERVICES {
            get {
                return ResourceManager.GetString("ERROR_FAILED_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompression failed..
        /// </summary>
        internal static string ERROR_FAILED_UNZIP {
            get {
                return ResourceManager.GetString("ERROR_FAILED_UNZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate ZIP archive..
        /// </summary>
        internal static string ERROR_FAILED_ZIP {
            get {
                return ResourceManager.GetString("ERROR_FAILED_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid services data..
        /// </summary>
        internal static string ERROR_INVALID_SERV_DATA {
            get {
                return ResourceManager.GetString("ERROR_INVALID_SERV_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading.
        /// </summary>
        internal static string ERROR_UPLOADING {
            get {
                return ResourceManager.GetString("ERROR_UPLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_add_item {
            get {
                object obj = ResourceManager.GetObject("icon_add_item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_computer_ok {
            get {
                object obj = ResourceManager.GetObject("icon_computer_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_computer_ok_small {
            get {
                object obj = ResourceManager.GetObject("icon_computer_ok_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_delete {
            get {
                object obj = ResourceManager.GetObject("icon_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_delete_small {
            get {
                object obj = ResourceManager.GetObject("icon_delete_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_donate2 {
            get {
                object obj = ResourceManager.GetObject("icon_donate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_down {
            get {
                object obj = ResourceManager.GetObject("icon_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_forum {
            get {
                object obj = ResourceManager.GetObject("icon_forum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_gear {
            get {
                object obj = ResourceManager.GetObject("icon_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_open {
            get {
                object obj = ResourceManager.GetObject("icon_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_questionmark {
            get {
                object obj = ResourceManager.GetObject("icon_questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_save {
            get {
                object obj = ResourceManager.GetObject("icon_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_tasks {
            get {
                object obj = ResourceManager.GetObject("icon_tasks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_up {
            get {
                object obj = ResourceManager.GetObject("icon_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_zip {
            get {
                object obj = ResourceManager.GetObject("icon_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available.{0}Please visit {1} to download new version..
        /// </summary>
        internal static string INFO_NEW_VERSION {
            get {
                return ResourceManager.GetString("INFO_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2013 Krkadoni.com - Released under The MIT License.
        ///
        ///Permission is hereby granted, free of charge, to any person
        ///obtaining a copy of this software and associated documentation
        ///files (the &quot;Software&quot;), to deal in the Software without
        ///restriction, including without limitation the rights to use,
        ///copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the
        ///Software is furnished to do so, subject to the following
        ///conditions:
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string MoveOptionsPage_MoveOptionsPage_Copy {
            get {
                return ResourceManager.GetString("MoveOptionsPage_MoveOptionsPage_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveOptionsPage_MoveOptionsPage_Move {
            get {
                return ResourceManager.GetString("MoveOptionsPage_MoveOptionsPage_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open2 {
            get {
                object obj = ResourceManager.GetObject("open2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string POSITION_COLUMN_HEADER {
            get {
                return ResourceManager.GetString("POSITION_COLUMN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value!.
        /// </summary>
        internal static string Profile_invalidValue_Invalid_value_ {
            get {
                return ResourceManager.GetString("Profile_invalidValue_Invalid_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0} already exists!.
        /// </summary>
        internal static string ProfilesOptionsPage_btnAdd_Click_Profile__0__already_exists_ {
            get {
                return ResourceManager.GetString("ProfilesOptionsPage_btnAdd_Click_Profile__0__already_exists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string ProfilesOptionsPage_btnAdd_Click_Warning {
            get {
                return ResourceManager.GetString("ProfilesOptionsPage_btnAdd_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QUESTION {
            get {
                return ResourceManager.GetString("QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        internal static string QUESTION_DELETE_TASK {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available. Would you like to download?.
        /// </summary>
        internal static string QUESTION_NEW_VERSION {
            get {
                return ResourceManager.GetString("QUESTION_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        internal static string SATELLITE_COLUMN_HEADER {
            get {
                return ResourceManager.GetString("SATELLITE_COLUMN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SELECT_COLUMN_HEADER {
            get {
                return ResourceManager.GetString("SELECT_COLUMN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        internal static string STATUS_CONNECTED_TO {
            get {
                return ResourceManager.GetString("STATUS_CONNECTED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to.
        /// </summary>
        internal static string STATUS_CONNECTING_TO {
            get {
                return ResourceManager.GetString("STATUS_CONNECTING_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing task.
        /// </summary>
        internal static string STATUS_PROCESSING_TASK {
            get {
                return ResourceManager.GetString("STATUS_PROCESSING_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading services.
        /// </summary>
        internal static string STATUS_READING_SERVICES {
            get {
                return ResourceManager.GetString("STATUS_READING_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select archive file with services.
        /// </summary>
        internal static string STATUS_SELECT_ARCHIVE {
            get {
                return ResourceManager.GetString("STATUS_SELECT_ARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select services file..
        /// </summary>
        internal static string STATUS_SELECT_SERVICES {
            get {
                return ResourceManager.GetString("STATUS_SELECT_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string TASKS_COLUMN_HEADER {
            get {
                return ResourceManager.GetString("TASKS_COLUMN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        internal static string UPLOADING {
            get {
                return ResourceManager.GetString("UPLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name..
        /// </summary>
        internal static string WARNING_INVALID_FILENAME {
            get {
                return ResourceManager.GetString("WARNING_INVALID_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid task name..
        /// </summary>
        internal static string WARNING_INVALID_TASKNAME {
            get {
                return ResourceManager.GetString("WARNING_INVALID_TASKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No satellites selected..
        /// </summary>
        internal static string WARNING_NO_SAT_SELECTED {
            get {
                return ResourceManager.GetString("WARNING_NO_SAT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected output directory does not exist!.
        /// </summary>
        internal static string WARNING_OUTDIR_NOTEXIST {
            get {
                return ResourceManager.GetString("WARNING_OUTDIR_NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another task has the same output folder..
        /// </summary>
        internal static string WARNING_SAME_OUTFOLDER1 {
            get {
                return ResourceManager.GetString("WARNING_SAME_OUTFOLDER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only ZIP files can have same output folders..
        /// </summary>
        internal static string WARNING_SAME_OUTFOLDER2 {
            get {
                return ResourceManager.GetString("WARNING_SAME_OUTFOLDER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has the same satellites selected..
        /// </summary>
        internal static string WARNING_SAME_SATELLITES {
            get {
                return ResourceManager.GetString("WARNING_SAME_SATELLITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another task has the same output filename..
        /// </summary>
        internal static string WARNING_TASK_SAME_OUT {
            get {
                return ResourceManager.GetString("WARNING_TASK_SAME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task with such name already exists..
        /// </summary>
        internal static string WARNING_TASKNAME_EXISTS {
            get {
                return ResourceManager.GetString("WARNING_TASKNAME_EXISTS", resourceCulture);
            }
        }
    }
}
